package ru.meand.mysli;

import android.app.*;
import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.*;
import android.graphics.*;
import android.os.Bundle;
import android.security.keystore.*;
import android.text.*;
import android.util.Base64;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;
import javax.crypto.*;
import javax.crypto.spec.GCMParameterSpec;

public class MainActivity extends Activity {
  static final String OWNER="an04wallt-spec",REPO="meand",BRANCH="main",PATH="blog.html";
  static final String MARK="<!-- BLOG_POSTS_START -->",KEY="mysli_github_key";
  final int bg=Color.rgb(20,11,8),surface=Color.rgb(33,18,13),copper=Color.rgb(194,133,91),text=Color.rgb(226,192,168),muted=Color.rgb(152,113,91);
  final ExecutorService worker=Executors.newSingleThreadExecutor();
  NotesDb db; LinearLayout root; EditText title,body; Button publish; TextView status; long noteId=-1; boolean editor,loading;

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);db=new NotesDb();showFeed();if(token().isEmpty())root.postDelayed(this::settings,350);}

  LinearLayout base(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(22),dp(18),dp(22),dp(18));v.setBackgroundColor(bg);v.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(dp(22),dp(18)+insets.getSystemWindowInsetTop(),dp(22),dp(18)+insets.getSystemWindowInsetBottom());return insets;});v.requestApplyInsets();return v;}
  TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
  View header(String label,String action,View.OnClickListener click){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView name=tv(label,27,copper);name.setTypeface(Typeface.create("sans-serif",0));name.setLetterSpacing(.12f);h.addView(name,new LinearLayout.LayoutParams(0,dp(56),1));TextView a=tv(action,action.equals("‹")?42:29,muted);a.setGravity(Gravity.CENTER);a.setOnClickListener(click);h.addView(a,new LinearLayout.LayoutParams(dp(56),dp(56)));return h;}

  void showFeed(){editor=false;noteId=-1;root=base();root.addView(header("МЫСЛИ","⚙",v->settings()));ScrollView scroll=new ScrollView(this);LinearLayout feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(12),0,dp(90));scroll.addView(feed);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));Cursor c=db.r().query("notes",null,null,null,null,null,"created_at DESC");if(!c.moveToFirst()){TextView e=tv("Здесь будут ваши заметки",21,muted);e.setGravity(Gravity.CENTER);feed.addView(e,new LinearLayout.LayoutParams(-1,dp(180)));}else do{feed.addView(note(c.getLong(0),c.getString(1),c.getString(2),c.getLong(3),c.getInt(4)==1));}while(c.moveToNext());c.close();Button add=new Button(this);add.setText("＋  НОВАЯ ЗАПИСЬ");add.setTextColor(bg);add.setTypeface(Typeface.DEFAULT_BOLD);add.setBackgroundTintList(android.content.res.ColorStateList.valueOf(copper));add.setOnClickListener(v->newNote());root.addView(add,new LinearLayout.LayoutParams(-1,dp(58)));setContentView(root);}

  View note(long id,String name,String value,long time,boolean sent){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(17),dp(15),dp(17),dp(15));card.setBackgroundColor(surface);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.bottomMargin=dp(12);card.setLayoutParams(cp);TextView n=tv(name.trim().isEmpty()?"Без заголовка":name,25,copper);card.addView(n);String date=new SimpleDateFormat("dd.MM.yyyy  HH:mm",Locale.getDefault()).format(new Date(time));TextView m=tv(date+(sent?"   ·   опубликовано":"   ·   черновик"),13,muted);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,-2);mp.topMargin=dp(7);card.addView(m,mp);TextView b=tv(value,19,text);b.setLineSpacing(0,1.32f);b.setVisibility(View.GONE);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.topMargin=dp(15);card.addView(b,bp);View.OnClickListener toggle=v->b.setVisibility(b.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);n.setOnClickListener(toggle);m.setOnClickListener(toggle);if(!sent){Button edit=new Button(this);edit.setText("ПРОДОЛЖИТЬ");edit.setTextColor(copper);edit.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(45,25,18)));edit.setOnClickListener(v->edit(id));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(46));ep.topMargin=dp(13);card.addView(edit,ep);}return card;}

  void newNote(){ContentValues v=new ContentValues();v.put("title","");v.put("body","");v.put("created_at",System.currentTimeMillis());v.put("published",0);edit(db.w().insertOrThrow("notes",null,v));}
  EditText input(String hint,boolean multi){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setTextColor(text);e.setBackgroundColor(surface);e.setPadding(dp(17),multi?dp(16):0,dp(17),multi?dp(16):0);e.setTextSize(multi?19:23);e.setInputType(InputType.TYPE_CLASS_TEXT|(multi?InputType.TYPE_TEXT_FLAG_MULTI_LINE:InputType.TYPE_TEXT_FLAG_CAP_SENTENCES));return e;}

  void edit(long id){editor=true;noteId=id;root=base();root.addView(header("НОВАЯ ЗАПИСЬ","‹",v->leave()));title=input("Заголовок",false);title.setSingleLine();LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,dp(62));tp.topMargin=dp(13);root.addView(title,tp);body=input("Текст записи…",true);body.setGravity(Gravity.TOP|Gravity.START);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,0,1);bp.topMargin=dp(14);bp.bottomMargin=dp(18);root.addView(body,bp);publish=new Button(this);publish.setText("ОПУБЛИКОВАТЬ");publish.setTextColor(bg);publish.setTypeface(Typeface.DEFAULT_BOLD);publish.setBackgroundTintList(android.content.res.ColorStateList.valueOf(copper));publish.setOnClickListener(v->publish());root.addView(publish,new LinearLayout.LayoutParams(-1,dp(58)));status=tv("Черновик сохраняется автоматически",14,muted);status.setGravity(Gravity.CENTER);root.addView(status,new LinearLayout.LayoutParams(-1,dp(46)));setContentView(root);Cursor c=db.r().query("notes",new String[]{"title","body"},"id=?",new String[]{""+id},null,null,null);loading=true;if(c.moveToFirst()){title.setText(c.getString(0));body.setText(c.getString(1));}loading=false;c.close();TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int x,int y){}public void onTextChanged(CharSequence s,int a,int x,int y){save();}public void afterTextChanged(Editable e){}};title.addTextChangedListener(w);body.addTextChangedListener(w);title.requestFocus();}
  void save(){if(loading||noteId<0||title==null)return;ContentValues v=new ContentValues();v.put("title",title.getText().toString());v.put("body",body.getText().toString());db.w().update("notes",v,"id=?",new String[]{""+noteId});}
  void leave(){save();if(title.getText().toString().trim().isEmpty()&&body.getText().toString().trim().isEmpty())db.w().delete("notes","id=?",new String[]{""+noteId});showFeed();}

  void publish(){save();String n=title.getText().toString().trim(),b=body.getText().toString().trim(),t=token();if(n.isEmpty()){msg("Введите заголовок",true);title.requestFocus();return;}if(b.isEmpty()){msg("Введите текст",true);body.requestFocus();return;}if(t.isEmpty()){settings();return;}busy(true);msg("Публикую…",false);long id=noteId;worker.execute(()->{try{send(t,n,b);ContentValues v=new ContentValues();v.put("published",1);db.w().update("notes",v,"id=?",new String[]{""+id});runOnUiThread(()->new AlertDialog.Builder(this).setMessage("Запись опубликована. На сайте она появится примерно через минуту.").setPositiveButton("Готово",(d,w)->showFeed()).setCancelable(false).show());}catch(Exception e){runOnUiThread(()->{busy(false);msg(error(e),true);});}});}
  void send(String token,String name,String value)throws Exception{String api="https://api.github.com/repos/"+OWNER+"/"+REPO+"/contents/"+PATH;HttpURLConnection g=open(api+"?ref="+BRANCH,"GET",token);int code=g.getResponseCode();String response=read(g,code);if(code!=200)throw new Exception("GET:"+code);JSONObject old=new JSONObject(response);String html=new String(Base64.decode(old.getString("content").replaceAll("\\s",""),Base64.DEFAULT),StandardCharsets.UTF_8);if(!html.contains(MARK))throw new Exception("MARKER");html=html.replace(MARK,MARK+"\n"+article(name,value));JSONObject data=new JSONObject();data.put("message","Publish: "+name);data.put("content",Base64.encodeToString(html.getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP));data.put("sha",old.getString("sha"));data.put("branch",BRANCH);HttpURLConnection p=open(api,"PUT",token);p.setDoOutput(true);byte[] bytes=data.toString().getBytes(StandardCharsets.UTF_8);try(OutputStream o=p.getOutputStream()){o.write(bytes);}code=p.getResponseCode();read(p,code);if(code!=200)throw new Exception("PUT:"+code);}
  String article(String n,String b){return "    <article class=\"entry is-collapsed\" id=\"post-"+UUID.randomUUID()+"\">\n      <button class=\"entry__title\" type=\"button\" aria-expanded=\"false\">\n        "+esc(n)+"\n      </button>\n      <div class=\"entry__body\"><div class=\"entry__body-inner\">\n        <p class=\"entry__text\">"+esc(b)+"</p>\n      </div></div>\n    </article>\n";}
  String esc(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
  HttpURLConnection open(String url,String method,String token)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/vnd.github+json");c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("X-GitHub-Api-Version","2022-11-28");c.setRequestProperty("Content-Type","application/json; charset=UTF-8");c.setRequestProperty("User-Agent","Meand-Mysli-Android");return c;}
  String read(HttpURLConnection c,int code)throws Exception{InputStream s=code>=200&&code<300?c.getInputStream():c.getErrorStream();if(s==null)return"";StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(s,StandardCharsets.UTF_8))){String x;while((x=r.readLine())!=null)b.append(x);}return b.toString();}

  void settings(){EditText key=new EditText(this);key.setHint("github_pat_…");key.setSingleLine();key.setInputType(129);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),0,dp(22),0);TextView help=tv("Введите ключ GitHub с доступом Contents: Read and write только к репозиторию an04wallt-spec/meand. Он хранится на телефоне в зашифрованном виде.",15,Color.DKGRAY);help.setPadding(0,dp(8),0,dp(16));box.addView(help);box.addView(key,new LinearLayout.LayoutParams(-1,dp(56)));AlertDialog d=new AlertDialog.Builder(this).setTitle("Настройка публикации").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String t=key.getText().toString().trim();if(t.isEmpty()){key.setError("Введите ключ");return;}try{saveToken(t);d.dismiss();}catch(Exception e){key.setError("Не удалось сохранить ключ");}}));d.show();}
  void saveToken(String t)throws Exception{SecretKey k=aes();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,k);String v=Base64.encodeToString(c.getIV(),2)+":"+Base64.encodeToString(c.doFinal(t.getBytes(StandardCharsets.UTF_8)),2);getPreferences(MODE_PRIVATE).edit().putString("token",v).apply();}
  String token(){String v=getPreferences(MODE_PRIVATE).getString("token","");if(v.isEmpty())return"";try{String[] p=v.split(":",2);KeyStore s=KeyStore.getInstance("AndroidKeyStore");s.load(null);SecretKey k=(SecretKey)s.getKey(KEY,null);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,k,new GCMParameterSpec(128,Base64.decode(p[0],2)));return new String(c.doFinal(Base64.decode(p[1],2)),StandardCharsets.UTF_8);}catch(Exception e){return"";}}
  SecretKey aes()throws Exception{KeyStore s=KeyStore.getInstance("AndroidKeyStore");s.load(null);if(s.containsAlias(KEY))return(SecretKey)s.getKey(KEY,null);KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(KEY,3).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());return g.generateKey();}
  void busy(boolean b){publish.setEnabled(!b);title.setEnabled(!b);body.setEnabled(!b);publish.setText(b?"ПУБЛИКУЮ…":"ОПУБЛИКОВАТЬ");}void msg(String s,boolean e){status.setText(s);status.setTextColor(e?Color.rgb(220,112,92):muted);}String error(Exception e){String s=e.getMessage()==null?"":e.getMessage();if(s.endsWith("401"))return"Ключ доступа не принят.";if(s.endsWith("403"))return"У ключа нет права на публикацию.";if(s.endsWith("409"))return"Страница изменилась. Нажмите ещё раз.";if(s.equals("MARKER"))return"На странице нет места для записей.";return"Не удалось опубликовать. Проверьте интернет.";}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
  @Override public void onBackPressed(){if(editor)leave();else super.onBackPressed();}
  @Override protected void onDestroy(){worker.shutdownNow();db.close();super.onDestroy();}
  class NotesDb extends SQLiteOpenHelper{NotesDb(){super(MainActivity.this,"mysli.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,created_at INTEGER NOT NULL,published INTEGER NOT NULL DEFAULT 0)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}SQLiteDatabase r(){return getReadableDatabase();}SQLiteDatabase w(){return getWritableDatabase();}}
}
